// Generated by spider on 2026-01-30 14:37:52.601291

class AppImages {
  AppImages._();

  static const String profilePlaceholder =
      'assets/images/profile_placeholder.webp';
  static const String promo1 = 'assets/images/promo_1.webp';
  static const String promo2 = 'assets/images/promo_2.webp';
  static const String promo3 = 'assets/images/promo_3.webp';
}
